### ISSUE TITLE
500000 baud rate

### ISSUE THREAD

**Issue by pepijndevos** [nyholku/purejavacomm#4]
I can get up to 460800, but I need 500000. When i try that, I get:

```
java.lang.IllegalStateException: JTermios call returned -1 at class jtermios.JTermios$JTermiosLogging line 459
    at purejavacomm.PureJavaSerialPort.checkReturnCode(PureJavaSerialPort.java:974)
    at purejavacomm.PureJavaSerialPort.setSerialPortParams(PureJavaSerialPort.java:548)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:92)
    at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:30)
    at dpscope.low$dpscope.invoke(low.clj:10)
    at user$eval75.invoke(NO_SOURCE_FILE:2)
    at clojure.lang.Compiler.eval(Compiler.java:6465)
    at clojure.lang.Compiler.eval(Compiler.java:6431)
    at clojure.core$eval.invoke(core.clj:2795)
    at clojure.main$repl$read_eval_print__5967.invoke(main.clj:244)
    at cuser=> lojure.main$repl$fn__5972.invoke(main.clj:265)
    at clojure.main$repl.doInvoke(main.clj:265)
    at clojure.lang.RestFn.invoke(RestFn.java:512)
    at user$eval27$acc__2839__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.AFn.run(AFn.java:24)
    at java.lang.Thread.run(Thread.java:680)
```

**Comment by jason-s** [comment]
just a clarification question: does PureJavaComm work with custom baud rates on OSX? (and Linux, for that matter) I know it works well on Windows; we use 625Kbaud and 4.375Kbaud all the time.

**Comment by nyholku** [comment]
Been a while so I don't recall if there was any conclusion ... basically the code is there and looks like it should work but I don't have hardware that I can try this with so you have to test it yourself.
